export interface ICustomer {
    _id:string
    code:string
    name:string
    waterMeterCode:string
    address:string
    tariffId:string
    glandId:string
    numberOfHouseholds:number
    numberOfPeople:number
    phoneNumber:string
    taxCode:string
    email:string
    contractCode:string
    contractDate:string
    chargeTypeId:string
    payTypeId:string
    environmentalProtectionFee:number
    bankId:string
    beginUse:string
    endUse:string
    active:boolean
}